version: “3.8”

volumes:
  mysql-data:

services:
  web:
    build: ./web
    ports:
      # - 80:80
      - 480:80
      - 481:81
      - 482:82
      - 483:83
      - 484:84
      # - 443:443
      - 1480:8000
      - 1481:8001
      - 1482:8002
      - 5173:5173
      # - 20:20
      # - 21:21
      # - 30001-30005:30001-30005
      # - 3000:3000
    restart: always
    volumes:
      - ./web/html:/var/www/html
      - ./web/volumes/apache2:/etc/apache2
      - ./web/volumes/php/8.1/apache2/php.ini:/etc/php/8.1/apache2/php.ini
      - ./web/volumes/phpMyAdmin:/usr/share/phpMyAdmin
      - ./web/volumes/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./web/volumes/ftp/vsftpd.conf:/etc/vsftpd.conf
      - ./web/volumes/ftp/ftp_dir:/var/www/ftp_dir
      - ./web/volumes/ftp/user_conf:/etc/vsftpd/user_conf
      - ./web/volumes/ftp/chroot_list:/etc/vsftpd/chroot_list
      - ./web/volumes/ftp/user_list:/etc/vsftpd/user_list
      - ./web/volumes/backup_db:/home/backup_db
    working_dir: /var/www/html
    tty: true
    platform: linux/x86_64
    privileged: true 
    depends_on: 
      - db

  db:
    build: ./db
    ports:
      # - 3306:3306
      - 406:3306
    restart: always
    platform: linux/x86_64
    environment:
      # MYSQL_USER: my_user
      # MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
       - mysql-data:/var/lib/mysql
    tty: true
    privileged: true 

